### ISSUE TITLE
Searching XDG directories for initialization files

### ISSUE THREAD

**Issue by magicant** [magicant/yash#19]
(Feature request migrated from https://osdn.net/projects/yash/ticket/46546)

It might be helpful if the shell honors the `$XDG_CONFIG_HOME` variable when looking for initialization scripts (profile and rcfile).

----

Unresolved questions

- [ ] How can the user set the `$XDG_CONFIG_HOME` variable before the shell gets started? Typically, user-specified variables are set in the initialization scripts. It does not make sense for a script to set a variable that defines its own pathname.

**Comment by unrealapex** [comment]
I would be interested in implementing this feature. I am not a very competent C programmer, however I think implementing this would be a good way to understand the workings of real C codebases.

Addressing the unresolved question you mentioned, [here's what the XDG spec has to say](https://specifications.freedesktop.org/basedir-spec/latest/index.html#variables):

> $XDG_CONFIG_HOME is either not set or empty, **a default equal to $HOME/.config should be used.**

We can use `$HOME/.config`. Z Shell gets around this same issue by defining an environment variable called [`ZDOTDIR`](https://zsh.sourceforge.io/Intro/intro_3.html) that points to the configuration directory. However, the profile file would need to be in `$HOME`. 

---
Looking at the original feature request. OP suggested putting the files in `$XDG_CONFIG_HOME`. I think it would be neater if they were in `$XDG_CONFIG_HOME/yash` instead.

**Comment by magicant** [comment]
Thank you for participating. You can find the code here: https://github.com/magicant/yash/blob/75d0ddf72e2cbc79f51b8963b1b60573f19b1776/yash.c#L259-L348
