### ISSUE TITLE
Many linting errors on man page.

### ISSUE THREAD

**Issue by vext01** [magicant/yash#34]
OpenBSD's `mandoc` command has a linter for shaking bugs out of man pages.

If you run `mandoc -Tlint yash.1`, you get lots of linter errors.

Some are style-related, like:
```
mandoc: yash.1:3289:305: STYLE: input text line longer than 80 bytes: Local variables may ...
```

but others are proper warnings, like:
```
mandoc: yash.1:12733:2: WARNING: skipping paragraph macro: sp after SS
```

I also notice that when you build an OpenBSD package of yash it says:
```
/usr/local/pobj/yash-2.55/fake-amd64/usr/local/man/ja/man1/yash.1: No one-line description, using filename "yash"
```

That last one I've seen before and have fixed like [this](https://github.com/openbsd/ports/blob/master/print/texlive/texmf/patches/patch-texmf-dist_doc_man_man1_bib2gls_1)

(I don't know if any of this matters to you, but I thought I'd mention it)

Thanks

**Comment by magicant** [comment]
The man page is auto-generated with [AsciiDoc](https://asciidoc.org/), so there is little that can be done on my side. You might want to report the issue to AsciiDoc developers.

**Comment by vext01** [comment]
Fair enough. Closing this.
