### ISSUE TITLE
python's venv activate script errors out

### ISSUE THREAD

**Issue by prez** [magicant/yash#62]
**Describe the bug**
```
. .venv/bin/activate
```
errors out with
```
.venv/bin/activate:34: syntax error: the parameter name is missing or invalid
.venv/bin/activate:34: syntax error: `fi' is missing
```

**To Reproduce**
1. Create a python venv
2. Source the activation script

**Additional context**

I've attached the `activate` script for your convenience
[activate.txt](https://github.com/user-attachments/files/17007740/activate.txt)

As this is a very standard workflow for python development, it would be great to have this fixed. Thank you!

**Comment by magicant** [comment]
Thank you for opening the issue.

In the script file you attached, the line `SCRIPT_PATH="${(%):-%x}"` contains a zsh-specific extension that is unlikely to be implemented in yash. Yash is designed to eagerly catch unsupported syntax, even in commands that are not executed, so unfortunately, this cannot be “fixed.”

To resolve this issue, the venv authors should consider rewriting this line to `eval 'SCRIPT_PATH="${(%):-%x}"'`. This way, the line will only be parsed if it is executed.

**Comment by ay-ex** [comment]
Same issue over here. 
@prez thank you for opening the issue over at uv, did get the activate script to work via patching?
I eval wrapped ZSH and KSH, as described by @magicant  , also checked for YASH_VERSION, 
but what would be the equivalent for BASH_SOURCE to get the activate script path in yash? 🤔 
(with the path hardcoded and OSTYPE set, activate works)

**Comment by prez** [comment]
@ay-ex No, I haven't attempted to patch it. It'd be nice to get the fix upstream, but in the meantime I'm just using bash to source it.
