### ISSUE TITLE
Dot completion does not complete parent folder of relative path

### ISSUE THREAD

**Issue by unrealapex** [magicant/yash#75]
**Describe the bug**
When trying to type the relative path of a folder, Yash's dot completion does not complete it.

**To Reproduce**
1. Set up test directory:
```
testdir/
└── bar
```
2. Type `. testdi`
3. Press <kbd>Tab</kbd>

**Expected behavior**
Dot completion would complete the parent directory name.

**Environment (please complete the following information):**
 - OS: Gentoo
 - Version: 6.10.11-gentoo-dist
 - Locale:  en_US.UTF-8

**Additional context**
Once the full name of the parent folder is given, Yash completes normally. Additionally it would be useful if dot completion only showed executable files instead of all files. Let me know if you would like me to make a separate issue about this.

**Comment by magicant** [comment]
> Additionally it would be useful if dot completion only showed executable files instead of all files.

Note that shell scripts do not need to have execute permissions set by `chmod`. Any text file can be passed to `.` as long as it contains shell commands.
