### ISSUE TITLE
Neovim completion

### ISSUE THREAD

**Issue by unrealapex** [magicant/yash#77]
**Is your feature request related to a problem? Please describe.**
I would like to use tab completion with Neovim's flags.

**Describe the solution you'd like**
Implement a completion file for Neovim.

**Describe alternatives you've considered**
N/A

**Additional context**
I can triage on contributing a completion script.

**Comment by florian-ariasu** [comment]
Do you use lazyvim?

**Comment by unrealapex** [comment]
I do not use LazyVim. I actually stopped using Neovim so I do not have much motivation to implement this completion script anymore.
